# Generated by Django 4.2.7 on 2025-10-25 04:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Total de Sessões')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total de Alunos')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Avaliação Média')),
                ('total_feedbacks', models.IntegerField(default=0, verbose_name='Total de Avaliações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Monitor')),
            ],
            options={
                'verbose_name': 'Relatório de Monitor',
                'verbose_name_plural': 'Relatórios de Monitores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_overall', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Geral')),
                ('rating_knowledge', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Conhecimento do Monitor')),
                ('rating_communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Comunicação')),
                ('rating_patience', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Paciência')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('was_helpful', models.BooleanField(default=True, verbose_name='Foi útil?')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Recomendaria?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anônimo')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='Monitor')),
                ('queue_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queue_management.queueentry', verbose_name='Entrada na Fila')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='monitoring_sessions.monitoringsession', verbose_name='Sessão')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
    ]
