# Generated by Django 4.2.7 on 2025-10-25 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Tópico/Dúvida')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('in_service', 'Em atendimento'), ('completed', 'Atendido'), ('cancelled', 'Cancelado')], default='waiting', max_length=20, verbose_name='Status')),
                ('position', models.IntegerField(default=0, verbose_name='Posição na Fila')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrada na Fila')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início do Atendimento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Atendimento')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='monitoring_sessions.monitoringsession', verbose_name='Sessão')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Entrada na Fila',
                'verbose_name_plural': 'Entradas na Fila',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
